### ISSUE TITLE
fix material switch

### ISSUE THREAD

**Issue by ArnaudWeyts** [punchtime/android#15]
Fix outline color on the switch & bug when the device locks itself.

**Comment by Haroenv** [comment]
mostly fix that it doesn't display what is currently in the preferences

**Comment by Haroenv** [comment]
I thought this wasn't fixed yet? Does it correspond to the setting now?

**Comment by ArnaudWeyts** [comment]
Whoops, setting does seem to correspond correctly, but when unloading the app and restarting, the app crashes everytime.

```
05-15 17:23:53.451 28662-28662/io.punchtime.punchtime E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.punchtime.punchtime, PID: 28662
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.ValueAnimator.setCurrentPlayTime(long)' on a null object reference
at com.github.glomadrian.materialanimatedswitch.painter.BallPainter$BallAnimatorListener.onAnimationUpdate(BallPainter.java:151)
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
at com.github.glomadrian.materialanimatedswitch.painter.BallPainter.setState(BallPainter.java:109)
at com.github.glomadrian.materialanimatedswitch.MaterialAnimatedSwitch.setState(MaterialAnimatedSwitch.java:143)
at com.github.glomadrian.materialanimatedswitch.MaterialAnimatedSwitch.doActionDown(MaterialAnimatedSwitch.java:168)
at com.github.glomadrian.materialanimatedswitch.MaterialAnimatedSwitch.toggle(MaterialAnimatedSwitch.java:182)
at io.punchtime.punchtime.ui.fragments.DashboardFragment$6.run(DashboardFragment.java:342)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by Haroenv** [comment]
I would give this low priority, since we won't implement the automatic mode.

**Comment by Haroenv** [comment]
It's corresponding to the setting now.
