### ISSUE TITLE
Calendar fragments crash the app

### ISSUE THREAD

**Issue by Haroenv** [punchtime/android#39]
```
 Process: io.punchtime.punchtime, PID: 5179
  com.firebase.client.FirebaseException: Failed to bounce to type
      at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:185)
      at io.punchtime.punchtime.logic.operations.PulseOperations$1.onDataChange(PulseOperations.java:36)
      at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:56)
      at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45)
      at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5294)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
   Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "time" (class io.punchtime.punchtime.data.Pulse), not marked as ignorable (10 known properties: , "checkout", "latitude", "checkin", "employee", "longitude", "note", "addressCityCountry", "addressStreet", "employer", "confirmed"])
      at [Source: java.io.StringReader@4871443; line: 1, column: 52] (through reference chain: io.punchtime.punchtime.data.Pulse["time"])
      at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
      at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
      at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
      at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:183)
      at io.punchtime.punchtime.logic.operations.PulseOperations$1.onDataChange(PulseOperations.java:36) 
      at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:56) 
      at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45) 
      at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38) 
      at android.os.Handler.handleCallback(Handler.java:739) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:135) 
      at android.app.ActivityThread.main(ActivityThread.java:5294) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:372) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

seems to expect `time` somewhere or finds `time` somewhere in the checkin

**Comment by Haroenv** [comment]
error found: `-KH45oElgdAJ9-04RQEt` had a `time` key for some reason (I guess used an old version of the app)
